---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/camel.svg
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: resturant
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.redhat
  name: resturant
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: resturant
    provider: fabric8
    group: com.redhat
